# Generated by Django 5.0.6 on 2026-07-22 09:58

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryzone',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, help_text="Og'irlikdan qat'i nazar olinadigan minimal narx", max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Asosiy narx (so'm)"),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='free_above_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Buyurtma shu summadan yuqori bo'lsa yetkazish bepul", max_digits=12, null=True, verbose_name="Bepul yetkazish limiti (so'm)"),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='is_default',
            field=models.BooleanField(default=False, help_text="Hech qaysi kalit so'z mos kelmasa shu zona qo'llanadi", verbose_name='Standart zona'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), help_text="Manzildan qidiriladigan so'zlar. Masalan: ['toshkent', 'tashkent', 'yunusobod']", size=None, verbose_name="Kalit so'zlar"),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='per_kg_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text="0 bo'lsa — og'irlik hisobga olinmaydi", max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name="1 kg uchun narx (so'm)"),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Kichik raqam — avval tekshiriladi', verbose_name='Tartib'),
        ),
    ]
