# Generated by Django 5.0.6 on 2026-07-22 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_name_alter_occasion_name_and_more'),
        ('leads', '0004_order_fulfillment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='catalog.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('closed', 'Yopilgan')], db_index=True, default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'courier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Kuryer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='leads.lead', verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Buyurtma paytidagi narx'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'landi"), ('in_progress', 'Tayyorlanmoqda'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
