# Generated by Django 5.0.6 on 2026-07-22 09:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_index=True, help_text="Katta harf bilan, bo'sh joysiz. Masalan: YOZGI25", max_length=50, unique=True, verbose_name='Kupon kodi'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text="Foiz uchun: 15 (ya'ni 15%). Summa uchun: 50000", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Chegirma miqdori'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Faqat foiz turi uchun — chegirma bu summadan oshmasin', max_digits=12, null=True, verbose_name="Maksimal chegirma (so'm)"),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text="Bo'sh qoldirilsa — cheksiz", null=True, verbose_name='Maksimal ishlatish soni'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Bu summadan past buyurtmaga qo'llanmaydi", max_digits=12, null=True, verbose_name='Minimal buyurtma summasi'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text="Bo'sh qoldirilsa — muddatsiz", null=True, verbose_name='Amal qilish tugashi'),
        ),
    ]
