# Generated by Django 5.0.6 on 2026-07-22 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_businessprofile_logo_logotype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessprofile',
            options={'verbose_name': 'Biznes profili', 'verbose_name_plural': 'Biznes profillari'},
        ),
        migrations.AlterModelOptions(
            name='courierprofile',
            options={'verbose_name': 'Kuryer profili', 'verbose_name_plural': 'Kuryer profillari'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Kompaniya nomi'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Bepul'), ('basic', 'Asosiy'), ('pro', 'Pro')], default='free', max_length=20, verbose_name='Tariflik reja'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'business'}, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courierprofile',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Mavjud'),
        ),
        migrations.AlterField(
            model_name='courierprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'courier'}, on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courierprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='Masalan: velosiped, mototsikl, avtomobil', max_length=50, verbose_name='Transport turi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('business', 'Biznes'), ('courier', 'Kuryer'), ('admin', 'Admin')], db_index=True, default='user', max_length=20, verbose_name='Rol'),
        ),
    ]
