# Generated by Django 5.0.6 on 2026-07-22 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0005_alter_businessprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Masalan: Bosh ofis, Do'kon, Omborxona", max_length=255, verbose_name='Manzil nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='users.businessprofile', verbose_name='Biznes profili')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_locations', to='locations.address', verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Biznes manzili',
                'verbose_name_plural': 'Biznes manzillari',
            },
        ),
    ]
