# Generated by Django 5.0.6 on 2026-07-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_businesslocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='address',
        ),
    ]
