# Generated by Django 5.0.6 on 2026-07-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='alt_text',
            field=models.CharField(blank=True, help_text='SEO va accessibility uchun', max_length=255, verbose_name='Alt matn'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False, help_text='User avatari yoki mahsulotning bosh rasmi', verbose_name='Asosiy'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text="Kichik raqam — oldinroq ko'rsatiladi", verbose_name='Tartib'),
        ),
    ]
