# Generated by Django 5.0.6 on 2026-07-22 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_tree_product_multi_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.ForeignKey(limit_choices_to={'role': 'business'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Biznes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='product',
            name='occasions',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.occasion', verbose_name='Munosabatlar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name="Narx (so'm)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Sarlavha'),
        ),
    ]
