# Generated by Django 5.0.6 on 2026-07-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_product_d800fc_idx',
            old_name='reviews_rev_product_created_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_product_ddc882_idx',
            old_name='reviews_rev_product_rating_idx',
        ),
    ]
